export const techTags = [
  "JavaScript",
  "Python",
  "Java",
  "TypeScript",
  "Ruby",
  "C++",
  "React",
  "Angular",
  "Vue",
  "Django",
  "Node.js",
  "Express",
  "HTML",
  "CSS",
  "GraphQL",
  "REST",
  "APIs",
  "Docker",
  "Kubernetes",
  "Git",
  "Webpack",
  "Babel",
  "Jenkins",
  "Agile",
  "Scrum",
  "DevOps",
  "Continuous Integration",
  "Test-Driven Development",
  "PostgreSQL",
  "MongoDB",
  "MySQL",
  "SQLite",
  "Redis",
  "Firebase",
  "AWS",
  "Azure",
  "Google Cloud",
  "Encryption",
  "OAuth",
  "Authentication",
  "Firewalls",
  "UI/UX",
  "Responsive Design",
  "Wireframes",
  "Prototyping",
  "User Testing",
  "AI",
  "Machine Learning",
  "AR/VR",
  "IoT",
];

export const knowledgeLevels = [
  "Expert in TailwindCSS",
  "Beginner in Three.js",
  "Advanced knowledge of MaterialUI and Shadcn",
  "Beginner Python user",
  "Learning AI",
  "Proficient in React",
  "Novice in GraphQL",
  "Beginner in C# and .NET",
  "Proficient in Git and Version Control",
  "Intermediate user of Docker",
  "Learning Cybersecurity Fundamentals",
];

// TODO: Fix icon list
export const tech = [
  "javascript",
  "typescript",
  "styledcomponents",
  "tailwind",
  "nodejs",
  "vscode",
  "materialui",
  "reactjs",
  // "Express.js",
  // "Svelte",
  // "Django",
  // "Jest",
  // "Mocha",
  // "Chai",
  // "Kubernetes",
  // "Terraform",
  // "GraphQL",
  // "MongoDB",
];
export const platformArray = [
  "twitter",
  "linkedIn",
  "instagram",
  "github",
  "dribble",
  "facebook",
];
